// openwebui/src/lib/components/chat/Messages/ThinkingBubble.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import Spinner from '$lib/components/common/Spinner.svelte';

	export let status: any = null;
	export let message: string = 'Thinking...';

	let prefersReducedMotion = false;

	onMount(() => {
		const mediaQuery = window.matchMedia('(prefers-reduced-motion: reduce)');
		prefersReducedMotion = mediaQuery.matches;
		
		const handler = (e: MediaQueryListEvent) => {
			prefersReducedMotion = e.matches;
		};
		mediaQuery.addEventListener('change', handler);
		return () => mediaQuery.removeEventListener('change', handler);
	});
</script>

<div 
	class="flex gap-3 max-w-[90%] animate-pulse"
	role="status"
	aria-live="polite"
	aria-label="Assistant is thinking"
>
	<div class="flex-shrink-0 mt-1">
		<div
			class="w-9 h-9 rounded-lg bg-purple-500/20 flex items-center justify-center border border-purple-500/30"
			aria-hidden="true"
		>
			{#if prefersReducedMotion}
				<Spinner className="size-4 text-purple-400" />
			{:else}
				<span class="flex gap-1" aria-hidden="true">
					<span class="w-1.5 h-1.5 bg-purple-400 rounded-full animate-bounce" style="animation-delay: 0ms;"></span>
					<span class="w-1.5 h-1.5 bg-purple-400 rounded-full animate-bounce" style="animation-delay: 150ms;"></span>
					<span class="w-1.5 h-1.5 bg-purple-400 rounded-full animate-bounce" style="animation-delay: 300ms;"></span>
				</span>
			{/if}
		</div>
	</div>
	<div class="flex-1">
		<div class="flex items-center gap-2 mb-1">
			<span class="text-xs font-semibold text-purple-400 uppercase tracking-wider">Thinking</span>
			{#if status?.description}
				<span class="text-xs text-gray-500 dark:text-gray-400">
					{status.description}
				</span>
			{/if}
		</div>
		<div class="bg-gray-800/30 dark:bg-gray-800/50 border border-gray-700/50 dark:border-gray-600/30 rounded-2xl rounded-tl-sm px-4 py-3">
			<div class="flex items-center gap-2 text-gray-400 dark:text-gray-500 text-sm">
				<span class="ml-2">{message}</span>
			</div>
		</div>
	</div>
</div>

{#if !prefersReducedMotion}
<style>
	@keyframes bounce {
		0%,
		60%,
		100% {
			transform: translateY(0);
		}
		30% {
			transform: translateY(-4px);
		}
	}

	.animate-bounce {
		animation: bounce 1s infinite;
	}
</style>
{/if}

// ui/components/ThinkingBubble.tsx
import React from 'react';

const ThinkingBubble: React.FC = () => {
  return (
    <div className="flex gap-4 max-w-[90%] animate-in fade-in slide-in-from-bottom-2 duration-300">
      <div className="flex-shrink-0 mt-1">
        <div className="w-10 h-10 rounded-xl bg-black/40 flex items-center justify-center border border-white/10 shadow-lg overflow-hidden relative">
          <div className="w-2 h-2 bg-purple-500 rounded-full animate-ping absolute opacity-75"></div>
          <div className="w-2 h-2 bg-purple-400 rounded-full relative"></div>
        </div>
      </div>
      <div className="flex-1 space-y-1.5">
        <div className="flex items-center gap-2">
           <span className="text-xs font-bold text-purple-300 uppercase tracking-wider">Heidi</span>
        </div>
        <div className="p-4 rounded-2xl rounded-tl-sm border border-white/5 bg-[#1a162e]/80 backdrop-blur-sm">
           <div className="flex flex-col gap-2 w-full max-w-[200px]">
              <div className="h-2 bg-white/10 rounded w-full animate-pulse"></div>
              <div className="h-2 bg-white/10 rounded w-2/3 animate-pulse delay-75"></div>
           </div>
        </div>
      </div>
    </div>
  );
};

export default ThinkingBubble;
